//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB08.AMIS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB08.AMIS.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng.
        /// </summary>
        public static string BankUnit {
            get {
                return ResourceManager.GetString("BankUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string Default_User {
            get {
                return ResourceManager.GetString("Default_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete to database return 0.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to database return 0.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updatedatabase return 0.
        /// </summary>
        public static string DevMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input field.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /^(([^&lt;&gt;()[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]/^(([^&lt;&gt;()[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.
        /// </summary>
        public static string EmailValidate {
            get {
                return ResourceManager.GetString("EmailValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Employee_Code {
            get {
                return ResourceManager.GetString("Employee_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        public static string IdentifyCode {
            get {
                return ResourceManager.GetString("IdentifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openapi.google.com/api/errorrcode.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openapi.google.com/api/errorrcode.
        /// </summary>
        public static string MoreInfo_InsertFaild {
            get {
                return ResourceManager.GetString("MoreInfo_InsertFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://openapi.google.com/api/errorrcode.
        /// </summary>
        public static string MoreInfo_Request {
            get {
                return ResourceManager.GetString("MoreInfo_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Number_Order {
            get {
                return ResourceManager.GetString("Number_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string Postions {
            get {
                return ResourceManager.GetString("Postions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_CheckDelete.
        /// </summary>
        public static string Proc_CheckDelete {
            get {
                return ResourceManager.GetString("Proc_CheckDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_CheckDulicate.
        /// </summary>
        public static string Proc_CheckDulicate {
            get {
                return ResourceManager.GetString("Proc_CheckDulicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteMultiple.
        /// </summary>
        public static string Proc_DeleteMultiple {
            get {
                return ResourceManager.GetString("Proc_DeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteRecord.
        /// </summary>
        public static string Proc_DeleteRecord {
            get {
                return ResourceManager.GetString("Proc_DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Filter.
        /// </summary>
        public static string Proc_Filter {
            get {
                return ResourceManager.GetString("Proc_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetMaxRecord.
        /// </summary>
        public static string Proc_GetMaxRecord {
            get {
                return ResourceManager.GetString("Proc_GetMaxRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_codenew_GetMaxRecord.
        /// </summary>
        public static string Proc_GetNewCode {
            get {
                return ResourceManager.GetString("Proc_GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_InsertRecord.
        /// </summary>
        public static string Proc_InsertRecord {
            get {
                return ResourceManager.GetString("Proc_InsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_SelectAllRecord.
        /// </summary>
        public static string Proc_SelectAllRecord {
            get {
                return ResourceManager.GetString("Proc_SelectAllRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_SelectRecord.
        /// </summary>
        public static string Proc_SelectRecord {
            get {
                return ResourceManager.GetString("Proc_SelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_product_SumRecord.
        /// </summary>
        public static string Proc_SumRecord {
            get {
                return ResourceManager.GetString("Proc_SumRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_codenew_UpdateRecord.
        /// </summary>
        public static string Proc_UpdateCode {
            get {
                return ResourceManager.GetString("Proc_UpdateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_UpdateRecord.
        /// </summary>
        public static string Proc_UpdateRecord {
            get {
                return ResourceManager.GetString("Proc_UpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:J1.
        /// </summary>
        public static string Range_Worksheet_Employee {
            get {
                return ResourceManager.GetString("Range_Worksheet_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:M1.
        /// </summary>
        public static string Range_Worksheet_Product {
            get {
                return ResourceManager.GetString("Range_Worksheet_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:D1.
        /// </summary>
        public static string Range_Worksheet_Supply {
            get {
                return ResourceManager.GetString("Range_Worksheet_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:F1.
        /// </summary>
        public static string Range_Worksheet_Warehouse {
            get {
                return ResourceManager.GetString("Range_Worksheet_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string Title_Worksheet_Employee {
            get {
                return ResourceManager.GetString("Title_Worksheet_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hàng hóa, dịch vụ.
        /// </summary>
        public static string Title_Worksheet_Product {
            get {
                return ResourceManager.GetString("Title_Worksheet_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm vật tư hàng hóa, dịch vụ.
        /// </summary>
        public static string Title_Worksheet_Supply {
            get {
                return ResourceManager.GetString("Title_Worksheet_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kho.
        /// </summary>
        public static string Title_Worksheet_Warehouse {
            get {
                return ResourceManager.GetString("Title_Worksheet_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thất bật.
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ Misa!.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        public static string UserMsg_InsertFaild {
            get {
                return ResourceManager.GetString("UserMsg_InsertFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string UserMsg_UpdateFaild {
            get {
                return ResourceManager.GetString("UserMsg_UpdateFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_ValidateFaild {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFaild", resourceCulture);
            }
        }
    }
}
